# Generated by Django 5.2.6 on 2025-09-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.IntegerField(blank=True, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=255, null=True)),
                ('avarage_price', models.IntegerField(blank=True, null=True)),
                ('climate_class', models.CharField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'User Data',
            },
        ),
    ]
